/* Generated by re2c 0.13.5 */
#line 1 ".\\src\\json_scanner.re2c"

/*
Copyright 2011-2011 Koutheir Attouchi. All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE FREEBSD PROJECT ``AS IS'' AND ANY EXPRESS OR
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
EVENT SHALL KOUTHEIR ATTOUCHI OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

The views and conclusions contained in the software and documentation are those
of the authors and should not be interpreted as representing official policies,
either expressed or implied, of Koutheir Attouchi.
*/

#include "json.h"

#line 62 ".\\src\\json_scanner.re2c"


int JSON::Scanner::ScanNextLexem()
{
	YYCTYPE at_cursor;

	for (;;) {
		m_current_state->location.column += (YYCURSOR - YYTOKEN);
		YYTOKEN = YYCURSOR;
		
		
#line 47 ".\\src\\json_scanner.re2c.cpp"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;

	if ((YYLIMIT - YYCURSOR) < 15) YYFILL(15);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\r':
	case ' ':	goto yy4;
	case '\n':	goto yy2;
	case '"':	goto yy10;
	case '+':
	case '-':	goto yy6;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy8;
	case 'f':	goto yy12;
	case 'n':	goto yy11;
	case 't':	goto yy13;
	default:	goto yy14;
	}
yy2:
	++YYCURSOR;
#line 75 ".\\\\src\\\\json_scanner.re2c"
	{
			m_current_state->location.NewLine();
			continue;	// Skip new line
		}
#line 84 ".\\src\\json_scanner.re2c.cpp"
yy4:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy102;
yy5:
#line 81 ".\\\\src\\\\json_scanner.re2c"
	{
			continue;	// Skip white space
		}
#line 94 ".\\src\\json_scanner.re2c.cpp"
yy6:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy92;
	default:	goto yy7;
	}
yy7:
#line 145 ".\\\\src\\\\json_scanner.re2c"
	{
			return *YYTOKEN;
		}
#line 115 ".\\src\\json_scanner.re2c.cpp"
yy8:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':	goto yy94;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy92;
	default:	goto yy9;
	}
yy9:
#line 95 ".\\\\src\\\\json_scanner.re2c"
	{
			at_cursor = *YYCURSOR;
			*YYCURSOR = '\0';
			yylval.number_int = strtoll(YYTOKEN, NULL, 10);
			*YYCURSOR = at_cursor;
			return json_integer_number;
		}
#line 141 ".\\src\\json_scanner.re2c.cpp"
yy10:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '+':
	case '-':	goto yy31;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy32;
	case 'T':
	case 't':	goto yy34;
	case 'b':	goto yy37;
	default:	goto yy30;
	}
yy11:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'u':	goto yy25;
	default:	goto yy7;
	}
yy12:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'a':	goto yy20;
	default:	goto yy7;
	}
yy13:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'r':	goto yy15;
	default:	goto yy7;
	}
yy14:
	yych = *++YYCURSOR;
	goto yy7;
yy15:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy17;
	default:	goto yy16;
	}
yy16:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy7;
	case 1: 	goto yy52;
	case 2: 	goto yy39;
	case 3: 	goto yy96;
	}
yy17:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy18;
	default:	goto yy16;
	}
yy18:
	++YYCURSOR;
#line 140 ".\\\\src\\\\json_scanner.re2c"
	{			
			return json_true;
		}
#line 213 ".\\src\\json_scanner.re2c.cpp"
yy20:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy21;
	default:	goto yy16;
	}
yy21:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy22;
	default:	goto yy16;
	}
yy22:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy23;
	default:	goto yy16;
	}
yy23:
	++YYCURSOR;
#line 135 ".\\\\src\\\\json_scanner.re2c"
	{
			return json_false;
		}
#line 238 ".\\src\\json_scanner.re2c.cpp"
yy25:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy26;
	default:	goto yy16;
	}
yy26:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy27;
	default:	goto yy16;
	}
yy27:
	++YYCURSOR;
#line 131 ".\\\\src\\\\json_scanner.re2c"
	{
			return json_null;
		}
#line 257 ".\\src\\json_scanner.re2c.cpp"
yy29:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy30:
	switch (yych) {
	case '"':	goto yy38;
	case '\\':	goto yy35;
	default:	goto yy29;
	}
yy31:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy32;
	default:	goto yy30;
	}
yy32:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 20) YYFILL(20);
	yych = *YYCURSOR;
	switch (yych) {
	case '"':	goto yy38;
	case '-':	goto yy70;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy32;
	case 'T':
	case 't':	goto yy71;
	case 'Z':
	case 'z':	goto yy59;
	case '\\':	goto yy35;
	default:	goto yy29;
	}
yy34:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':	goto yy55;
	case '2':	goto yy56;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy57;
	default:	goto yy30;
	}
yy35:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '"':	goto yy54;
	case '\\':	goto yy35;
	default:	goto yy29;
	}
yy37:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy40;
	default:	goto yy30;
	}
yy38:
	++YYCURSOR;
yy39:
#line 122 ".\\\\src\\\\json_scanner.re2c"
	{
			at_cursor = *YYCURSOR;
			*YYCURSOR = '\0';
			json_unescape_string(&yylval.string.data, &yylval.string.length, YYTOKEN + 1, yyleng - 2);
			*YYCURSOR = at_cursor;
			return json_string;
		}
#line 348 ".\\src\\json_scanner.re2c.cpp"
yy40:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy41;
	default:	goto yy30;
	}
yy41:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy42;
	default:	goto yy30;
	}
yy42:
	yych = *++YYCURSOR;
	switch (yych) {
	case '8':	goto yy43;
	default:	goto yy30;
	}
yy43:
	yych = *++YYCURSOR;
	switch (yych) {
	case '5':	goto yy44;
	default:	goto yy30;
	}
yy44:
	yych = *++YYCURSOR;
	switch (yych) {
	case ':':	goto yy45;
	default:	goto yy30;
	}
yy45:
	yych = *++YYCURSOR;
	switch (yych) {
	case '<':	goto yy46;
	default:	goto yy30;
	}
yy46:
	yych = *++YYCURSOR;
	switch (yych) {
	case '~':	goto yy47;
	default:	goto yy30;
	}
yy47:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '"':	goto yy51;
	case '\\':	goto yy49;
	default:	goto yy47;
	}
yy49:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '"':	goto yy53;
	case '\\':	goto yy49;
	default:	goto yy47;
	}
yy51:
	++YYCURSOR;
yy52:
#line 113 ".\\\\src\\\\json_scanner.re2c"
	{
			at_cursor = *YYCURSOR;
			*YYCURSOR = '\0';
			json_unescape_string(&yylval.string.data, &yylval.string.length, YYTOKEN + 8, yyleng - 9);
			*YYCURSOR = at_cursor;
			return json_binary;
		}
#line 420 ".\\src\\json_scanner.re2c.cpp"
yy53:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '"':	goto yy51;
	case '\\':	goto yy49;
	default:	goto yy47;
	}
yy54:
	yyaccept = 2;
	YYMARKER = ++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '"':	goto yy38;
	case '\\':	goto yy35;
	default:	goto yy29;
	}
yy55:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy57;
	case ':':	goto yy58;
	case 'Z':
	case 'z':	goto yy59;
	default:	goto yy30;
	}
yy56:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':	goto yy57;
	case ':':	goto yy58;
	case 'Z':
	case 'z':	goto yy59;
	default:	goto yy30;
	}
yy57:
	yych = *++YYCURSOR;
	switch (yych) {
	case ':':	goto yy58;
	case 'Z':
	case 'z':	goto yy59;
	default:	goto yy30;
	}
yy58:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':	goto yy62;
	case '6':
	case '7':
	case '8':
	case '9':	goto yy63;
	default:	goto yy30;
	}
yy59:
	yych = *++YYCURSOR;
	switch (yych) {
	case '"':	goto yy60;
	default:	goto yy30;
	}
yy60:
	++YYCURSOR;
#line 104 ".\\\\src\\\\json_scanner.re2c"
	{
			at_cursor = *YYCURSOR;
			*YYCURSOR = '\0';
			json_unescape_string(&yylval.string.data, &yylval.string.length, YYTOKEN + 1, yyleng - 2);
			*YYCURSOR = at_cursor;
			return json_datetime;
		}
#line 510 ".\\src\\json_scanner.re2c.cpp"
yy62:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy63;
	case ':':	goto yy64;
	case 'Z':
	case 'z':	goto yy59;
	default:	goto yy30;
	}
yy63:
	yych = *++YYCURSOR;
	switch (yych) {
	case ':':	goto yy64;
	case 'Z':
	case 'z':	goto yy59;
	default:	goto yy30;
	}
yy64:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':	goto yy65;
	case '6':
	case '7':
	case '8':
	case '9':	goto yy66;
	default:	goto yy30;
	}
yy65:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':	goto yy67;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy66;
	case 'Z':
	case 'z':	goto yy59;
	default:	goto yy30;
	}
yy66:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':	goto yy67;
	case 'Z':
	case 'z':	goto yy59;
	default:	goto yy30;
	}
yy67:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy68;
	default:	goto yy30;
	}
yy68:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy69;
	case 'Z':
	case 'z':	goto yy59;
	default:	goto yy30;
	}
yy69:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'Z':
	case 'z':	goto yy59;
	default:	goto yy30;
	}
yy70:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':	goto yy84;
	case '1':	goto yy85;
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy86;
	default:	goto yy30;
	}
yy71:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':	goto yy72;
	case '2':	goto yy73;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy74;
	default:	goto yy30;
	}
yy72:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy74;
	case ':':	goto yy75;
	case 'Z':
	case 'z':	goto yy59;
	default:	goto yy30;
	}
yy73:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':	goto yy74;
	case ':':	goto yy75;
	case 'Z':
	case 'z':	goto yy59;
	default:	goto yy30;
	}
yy74:
	yych = *++YYCURSOR;
	switch (yych) {
	case ':':	goto yy75;
	case 'Z':
	case 'z':	goto yy59;
	default:	goto yy30;
	}
yy75:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':	goto yy76;
	case '6':
	case '7':
	case '8':
	case '9':	goto yy77;
	default:	goto yy30;
	}
yy76:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy77;
	case ':':	goto yy78;
	case 'Z':
	case 'z':	goto yy59;
	default:	goto yy30;
	}
yy77:
	yych = *++YYCURSOR;
	switch (yych) {
	case ':':	goto yy78;
	case 'Z':
	case 'z':	goto yy59;
	default:	goto yy30;
	}
yy78:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':	goto yy79;
	case '6':
	case '7':
	case '8':
	case '9':	goto yy80;
	default:	goto yy30;
	}
yy79:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':	goto yy81;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy80;
	case 'Z':
	case 'z':	goto yy59;
	default:	goto yy30;
	}
yy80:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':	goto yy81;
	case 'Z':
	case 'z':	goto yy59;
	default:	goto yy30;
	}
yy81:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy82;
	default:	goto yy30;
	}
yy82:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy83;
	case 'Z':
	case 'z':	goto yy59;
	default:	goto yy30;
	}
yy83:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'Z':
	case 'z':	goto yy59;
	default:	goto yy30;
	}
yy84:
	yych = *++YYCURSOR;
	switch (yych) {
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy86;
	default:	goto yy30;
	}
yy85:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy87;
	case '0':
	case '1':
	case '2':	goto yy86;
	case 'T':
	case 't':	goto yy71;
	case 'Z':
	case 'z':	goto yy59;
	default:	goto yy30;
	}
yy86:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy87;
	case 'T':
	case 't':	goto yy71;
	case 'Z':
	case 'z':	goto yy59;
	default:	goto yy30;
	}
yy87:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':	goto yy88;
	case '1':
	case '2':	goto yy89;
	case '3':	goto yy90;
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy91;
	default:	goto yy30;
	}
yy88:
	yych = *++YYCURSOR;
	switch (yych) {
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy91;
	default:	goto yy30;
	}
yy89:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy91;
	case 'T':
	case 't':	goto yy71;
	case 'Z':
	case 'z':	goto yy59;
	default:	goto yy30;
	}
yy90:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':	goto yy91;
	case 'T':
	case 't':	goto yy71;
	case 'Z':
	case 'z':	goto yy59;
	default:	goto yy30;
	}
yy91:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy71;
	case 'Z':
	case 'z':	goto yy59;
	default:	goto yy30;
	}
yy92:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '.':	goto yy94;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy92;
	default:	goto yy9;
	}
yy94:
	yyaccept = 3;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy94;
	case 'E':
	case 'e':	goto yy97;
	default:	goto yy96;
	}
yy96:
#line 86 ".\\\\src\\\\json_scanner.re2c"
	{
			at_cursor = *YYCURSOR;
			*YYCURSOR = '\0';
			yylval.number_double = strtod(YYTOKEN, NULL);
			*YYCURSOR = at_cursor;
			return json_double_number;
		}
#line 958 ".\\src\\json_scanner.re2c.cpp"
yy97:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy98;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy99;
	default:	goto yy16;
	}
yy98:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy99;
	default:	goto yy16;
	}
yy99:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy99;
	default:	goto yy96;
	}
yy101:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy102:
	switch (yych) {
	case '\t':
	case '\r':
	case ' ':	goto yy101;
	default:	goto yy5;
	}
}
#line 149 ".\\src\\json_scanner.re2c"

	}
}
